### PR TITLE
mull-cxx: raise error if Elements reporter is used without compilation DB

### LINKED ISSUE #783: mull-cxx crashed on use --reporters=Elements
### Description

mull-cxx crashed on use `--reporters=Elements`:
```
mull-cxx: /__w/mull/mull/lib/AST/ASTMutationStorage.cpp:37: const mull::ASTMutation &mull::ASTMutationStorage::getMutation(const std::string &, mull::MutatorKind, int, int) const: Assertion `storage.count(sourceFile) > 0' failed.
Aborted (core dumped)
```

Everything is fine on execution without option `--reporters=Elements`.

### How to reproduce:

```
$ git clone https://github.com/tarantool/tarantool
$ cd tarantool
$ mkdir build && cd build
$ cmake \
  -DCMAKE_CXX_FLAGS="-fembed-bitcode -g -O0" \
  -DCMAKE_BUILD_TYPE=Debug \ 
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCMAKE_C_COMPILER="/usr/bin/clang" \
  -DCMAKE_CXX_COMPILER="/usr/bin/clang++" ..
$ make -j
$ mull-cxx -test-framework=CustomTest --reporters=Elements ./test/unit/int96.test
$ 
```

```
sergeyb@pony:~/sources/MRG/tarantool/build$ mull-cxx --version
Mull: LLVM-based mutation testing
https://github.com/mull-project/mull
Version: 0.8.0
Commit: 84f2f4d
Date: 13 Oct 2020
LLVM: 10.0.0
```

Ubuntu Focal 20.04 x86_64

### PR DESCRIPTION
**Pull request by stanislaw**
Closes #783

### CODE REVIEW

File: tools/mull-cxx/CLIOptions.cpp [hunk 1]
```diff
@@ -257,6 +258,10 @@ std::vector<std::unique_ptr<Reporter>> ReportersCLIOptions::reporters(ReporterPa
       reporters.emplace_back(new mull::SQLiteReporter(diagnostics, directory, name));
     } break;
     case ReporterKind::Elements: {
+      if (!params.compilationDatabaseAvailable) {
```
Comment (AlexDenisov) [inline tools/mull-cxx/CLIOptions.cpp:261]: I'm not 100% sure if this should go here, but we can find a better place eventually.

**Review by AlexDenisov — APPROVED** [review]

File: tools/mull-cxx/CLIOptions.cpp (hunk 1 above)
Comment (stanislaw) [reply tools/mull-cxx/CLIOptions.cpp:261]: Me too 😄
